[tool.poetry]
name = "tutorial"
version = "0.1.0"
description = ""
authors = ["hayato"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
transformers = "^4.32.1"
datasets = "^2.14.4"
evaluate = "^0.4.0"
tensorboard = "^2.14.0"
sentencepiece = "^0.1.99"
protobuf = "^4.24.2"
torch = "^2.0.1"
jupyter = "^1.0.0"
bitsandbytes = "^0.41.1"
accelerate = "^0.22.0"
loralib = "^0.1.2"
scipy = "^1.11.2"
peft = "^0.5.0"
openai = "^0.28.0"
pandas = "^2.1.0"
scikit-learn = "^1.3.0"
rouge-score = "^0.1.2"
utils = "^1.0.1"
fire = "^0.5.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.7.0"
isort = "^5.12.0"
mypy = "^1.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
